import { Officer, OfficerData } from "../../types";

const OfficerList: OfficerData = {
    Admin: {
        data: [
            {
                name: "Ryan Hopke",
                positions: "President",
                image: "/assets/team/Spring2024Officers/Ryan Hopke - President.jpg",
                section: "Admin",
                year: "Junior",
                major: "Mechanical Engineering",
                yearsOnTeam: "3",
                email: "ryan.hopke@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/ryan-hopke/",
            },
            {
                name: "Jennifer Briseno",
                positions: "Vice President",
                image: "/assets/team/Spring2024Officers/Jennifer Briseno - Vice President.jpg",
                section: "Admin",
                year: "Junior",
                major: "Mechanical Engineering",
                yearsOnTeam: "2",
                email: "jennifer.briseno@utdallas.edu",
                linkedin: "https://linkedin.com/in/jenniferbriseno002",
            },
            {
                name: "Aaryan Patel",
                positions: "Secretary",
                section: "Admin",
                image: "/assets/team/Spring2024Officers/Aaryan Patel - Secretary.jpg",
                email: "aaryan.patel@utdallas.edu",
            },
            {
                name: "Dennis Yermakov",
                positions: "Business Director",
                section: "Admin",
                year: "Junior",
                major: "ITSS",
                yearsOnTeam: "3",
                image: "/assets/team/Spring2024Officers/Dennis Yermakov - Business Director.jpg",
                email: "dennis.yermakov@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/dennis-yermakovs-profile",
            },
            {
                name: "Abby Ayala",
                positions: "Treasurer",
                section: "Admin",
                year: "Sophomore",
                major: "Biomedical Engineering | Software Minor",
                yearsOnTeam: "1.5",
                image: "/assets/team/Spring2024Officers/Abby Ayala - Treasurer.jpg",
                email: "abby.ayala@utdallas.edu",
            },
            {
                name: "Safaa Siddiqui",
                positions: "Treasurer",
                section: "Admin",
                year: "Freshman",
                major: "Business Analytics + Data Science",
                yearsOnTeam: "1",
                image: "/assets/team/Spring2024Officers/Safaa Siddiqui - Treasurer.jpg",
                email: "safaa.siddiqui@utdallas.edu",
            },
            {
                name: "Zheer Seyan",
                positions: "Chief Engineer | Suspension",
                section: "Admin",
                year: "Junior",
                major: "Mechanical Engineering",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Zheer Seyan - Chief Engineer 2025.jpg",
                email: "zheer.seyan@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/zheer-seyan-ab157b239/",
            },
            {
                name: "Grant Mitchell",
                positions: "Chief Engineer",
                section: "Admin",
                year: "Junior",
                major: "Mechanical Engineering",
                yearsOnTeam: "3",
                image: "/assets/team/Spring2024Officers/Grant Mitchell - Chief Engineer 2024.jpg",
                email: "grant.mitchell@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/grantmitchell101/",
            },
            {
                name: "Manuel De Jesus Contreras",
                positions: "Chief Engineer",
                section: "Admin",
                year: "Sophomore",
                major: "Electrical Engineering",
                yearsOnTeam: "2",
                image: "/assets/team/Headshots/Manuel.png",
                email: "manuel.dejesuscontreras@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/manuel-djc/",
            },
            {
                name: "Renee Menezes",
                positions: "Media Director",
                section: "Admin",
                year: "Freshman",
                major: "Psychology",
                yearsOnTeam: "0.5",
                image: "/assets/team/Spring2024Officers/Renee Menezes - Media.jpg",
                email: "renee.menezes@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/ren%C3%A9e-menezes-815296291/",
            },
            {
                name: "Hayden Bell",
                section: "Admin",
                year: "Senior",
                major: "Computer Science | Physics Minor",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Hayden Bell.jpg",
                email: "hayden.bell@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/hayden-bell-3687a9257/",
            },
        ],
    },
    Business: {
        data: [
            {
                name: "Nabeel Salman",
                positions: "Corporate Relations",
                section: "Business",
                year: "Sophomore",
                major: "Software Engineering",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Nabeel Salman - Corporate Relations.jpg",
                email: "nabeel.salman@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/nabeel-salman-31806421a/",
            },
        ],
    },
    Engineering: {
        data: [
            {
                name: "John McAlister",
                positions: "Aerodynamics",
                image: "/assets/team/Spring2024Officers/John McAlister - Aerodynamics.jpg",
                section: "Engineering",
                major: "Mechanical Engineering",
                year: "Junior",
                yearsOnTeam: "1",
                email: "john.mcalister@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/john-mcalister-067852286/",
            },
            {
                name: "Ethan Gamero",
                positions: "Chassis",
                section: "Engineering",
                major: "Mechanical Engineering",
                year: "Senior",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Ethan Gamero - Chassis.jpg",
                email: "ethan.gamero@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/ethan-g-400412135/",
            },
            {
                name: "Derek Fuhr",
                positions: "Composites",
                section: "Engineering",
                major: "Mechanical Engineering",
                year: "Junior",
                yearsOnTeam: "1",
                image: "/assets/team/Spring2024Officers/Derek Fuhr - Composites.jpg",
                email: "derek.fuhr@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/derek-fuhr/",
            },
            {
                name: "Sam Madhanmohan",
                positions: "Composites",
                section: "Engineering",
                major: "Mechanical Engineering",
                year: "Senior",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Sam Madhanmohan - Composites.jpg",
                email: "sam.madhanmohan@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/sam-madhanmohan-96b645289/",
            },
            {
                name: "Nate Ho",
                positions: "Electrical",
                section: "Engineering",
                major: "Electrical Engineering",
                year: "Senior",
                yearsOnTeam: "3",
                image: "/assets/team/Spring2024Officers/Nate Ho - Electrical.jpg",
                email: "nate.ho@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/nathaniel-ho-008ab2203/",
            },
            {
                name: "Cristian Cruz",
                positions: "Embedded",
                section: "Engineering",
                major: "Computer Engineering",
                year: "Senior",
                yearsOnTeam: "3.5",
                image: "/assets/team/Headshots/ChristianCruz.png",
                email: "cristian.cruzlopez@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/crsz/",
            },
            {
                name: "Zoe Lao",
                positions: "Ergonomics",
                section: "Engineering",
                image: "/assets/team/Spring2024Officers/Zoe Lao - Ergonomics.jpg",
                email: "zoe.lao@utdallas.edu",
            },
            {
                name: "Nolan Westrope",
                positions: "Manufacturing",
                section: "Engineering",
                year: "Junior",
                major: "Mechanical Engineering",
                yearsOnTeam: "3",
                image: "/assets/team/Spring2024Officers/Nolan Westrope - Manufacturing.jpg",
                email: "nolan.westrope@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/nolan-westrope-3198ba1b3/",
            },
            {
                name: "Brandon Shaffer",
                positions: "Powertrain",
                section: "Engineering",
                image: "/assets/team/Spring2024Officers/Brandon Shaffer - Powertrain.jpg",
                email: "brandon.shaffer@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/brandon-shaffer-93b013179/",
            },
            {
                name: "Noel Johnson",
                positions: "Software",
                section: "Engineering",
                year: "Senior",
                major: "Computer Science",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Noel Johnson - Software.jpg",
                email: "noel.johnson@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/noel-j-3b82b5105/",
            },
            {
                name: "Dillon Saulsberry",
                positions: "Steering",
                section: "Engineering",
                year: "Junior",
                major: "Mechanical Engineering",
                yearsOnTeam: "3",
                image: "/assets/team/Spring2024Officers/Dillon Saulsberry - Steering.jpg",
                email: "dillon.saulsberry@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/dillon-saulsberry/",
            },
            {
                name: "Apurva Betgar",
                positions: "2019 Rebuild Chief Engineer",
                section: "Engineering",
                year: "Freshman",
                major: "Computer Engineering",
                yearsOnTeam: "0.5",
                image: "/assets/team/Spring2024Officers/Apurva Betgar - 2019 Rebuild Chief Engineer.jpg",
                email: "apurva.betgar@utdallas.edu",
                linkedin: "www.linkedin.com/in/apurva-betgar",
            },
            {
                name: "Rayyan Sappayani",
                section: "Engineering",
                year: "Senior",
                major: "Mechanical Engineering",
                yearsOnTeam: "4",
                image: "/assets/team/Headshots/RayyanSappayani.png",
                email: "rayyan.sappayani@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/rayyan-sappayani-92230b191",
            },
        ],
    },
    EV: {
        data: [
            {
                name: "Connor Myers",
                positions: "Mechanical",
                section: "EV",
                year: "Junior",
                major: "Mechanical Engineering",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Connor Myers - EV Mechanical.jpg",
                email: "connor.myers2@utdallas.edu",
                linkedin: "LinkedIn.com/in/connor-my/",
            },
            {
                name: "Alan Frias",
                positions: "Electrical",
                section: "EV",
                year: "Senior",
                major: "Electrical Engineering",
                yearsOnTeam: "3",
                image: "/assets/team/Spring2024Officers/Alan Frias - EV Electrical.jpg",
                email: "alan.frias@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/alan-frias-utd-ee/",
            },
            {
                name: "Matthew Carolla",
                positions: "Powertrain",
                section: "EV",
                year: "Sophomore",
                major: "Mechanical Engineering",
                yearsOnTeam: "2",
                image: "/assets/team/Spring2024Officers/Matthew Carolla - EV Powertrain.jpg",
                email: "matthew.carolla@utdallas.edu",
                linkedin:
                    "https://www.linkedin.com/in/matthew-carolla-1b4b36281",
            },
            {
                name: "Chad Melhem",
                positions: "Embedded",
                section: "EV",
                year: "Junior",
                major: "Electrical Engineering",
                yearsOnTeam: "3",
                image: "/assets/team/Spring2024Officers/Chad Melhem - EV Embedded.jpg",
                email: "chad.melhem@utdallas.edu",
                linkedin: "https://www.linkedin.com/in/chadmelhem/",
            },
        ],
    },
};

export default OfficerList;
